name: mobile_kit
description: "A new Flutter package project."
version: 1.0.0
publist_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  currency_text_input_formatter: ^2.2.3
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  nil: ^1.1.1
  qr_code_scanner: ^1.0.1
  syncfusion_flutter_charts: ^25.2.6
  extended_image: ^8.2.0
  lottie: ^2.7.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  uses-material-design: true

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg : true