name: jala_app
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  qr_code_scanner: ^1.0.1
  get: ^4.6.6
  app_dependencies:
    path: ../../app_dependencies
  flutter_flavorizr: ^2.2.3
  json_annotation: ^4.8.1
  webview_flutter: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
      flavorDimensions: flavor-type
  flavors:
    prod:
      app:
        name: Jala App
      android:
        applicationId: id.jala.mobile
    dev:
      app:
        name: Jala App Dev
      android:
        applicationId: id.jala.mobile.dev
flutter:
  uses-material-design: true
